<a href="https://colab.research.google.com/github/cloudy-windy-rainy/jubilant-parakeet/blob/gh-pages/00_test_idec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# code cell
print("hello world")

hello world


In [ ]:
# Title1 
## Title2

In [ ]:
import torch
import numpy as np
from torch import nn # nn: torch의 하위 모듈
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor
import matplotlib.pyplot as plt
import warnings
#select multiline -> 'ctrl+/'=>multiline comment
#print option
torch.set_printoptions(precision=4, linewidth=50000, sci_mode = None)
#control warning message
warnings.filterwarnings(action='ignore')

In [ ]:
a = torch.rand(3,3)
a

tensor([[0.606196, 0.923512, 0.580965],
        [0.847347, 0.012546, 0.676202],
        [0.769760, 0.444146, 0.992851]])

In [ ]:
dataset_dir='~/dataset'
train_data = datasets.MNIST(root= dataset_dir, train = True, download = True, transform= ToTensor())
test_data = datasets.MNIST(root= dataset_dir , train = False, download= True, transform= ToTensor())
train_data



  0%|          | 0/9912422 [00:00<?, ?it/s]

Extracting /root/dataset/MNIST/raw/train-images-idx3-ubyte.gz to /root/dataset/MNIST/raw



  0%|          | 0/28881 [00:00<?, ?it/s]

Extracting /root/dataset/MNIST/raw/train-labels-idx1-ubyte.gz to /root/dataset/MNIST/raw



  0%|          | 0/1648877 [00:00<?, ?it/s]

Extracting /root/dataset/MNIST/raw/t10k-images-idx3-ubyte.gz to /root/dataset/MNIST/raw



  0%|          | 0/4542 [00:00<?, ?it/s]

Extracting /root/dataset/MNIST/raw/t10k-labels-idx1-ubyte.gz to /root/dataset/MNIST/raw



Dataset MNIST
    Number of datapoints: 60000
    Root location: /root/dataset
    Split: Train
    StandardTransform
Transform: ToTensor()

In [ ]:
test_data


Dataset MNIST
    Number of datapoints: 10000
    Root location: /root/dataset
    Split: Test
    StandardTransform
Transform: ToTensor()

In [ ]:
print('[print]Type of trainData:', type(train_data))
print('[print]Type of trainData.data :',type(train_data))
print('[print]Type of trainData.targets:',type(train_data.targets))
print('[print]Type of trainData.classes:',type(train_data.classes))



[print]Type of trainData: <class 'torchvision.datasets.mnist.MNIST'>
[print]Type of trainData.data : <class 'torchvision.datasets.mnist.MNIST'>
[print]Type of trainData.targets: <class 'torch.Tensor'>
[print]Type of trainData.classes: <class 'list'>


In [ ]:
print(train_data.targets)
print(train_data.classes)


tensor([5, 0, 4,  ..., 5, 6, 8])
['0 - zero', '1 - one', '2 - two', '3 - three', '4 - four', '5 - five', '6 - six', '7 - seven', '8 - eight', '9 - nine']


In [ ]:
print(train_data.data[0])

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 170, 253, 253, 253, 253, 253, 2

In [ ]:
#[0][0]: 3-D image data [0][1]:label


print(f'Image:{train_data[0][0].size()}')
print(f'Label:{train_data[0][1]}')


Image:torch.Size([1, 28, 28])
Label:5


In [ ]:
print(f'trainData.data:{train_data.data[0][24][4]}')
print(f'trainData.data/255:{train_data.data[0][24][4]/255}')
print(f'trainData:{train_data[0][0][0][24][4]}')


trainData.data:136
trainData.data/255:0.5333333611488342
trainData:0.5333333611488342
